"""empty message

Revision ID: 9ec947778f7b
Revises: 
Create Date: 2021-07-29 22:13:11.897000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec947778f7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_statuses',
    sa.Column('machine_status_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('machine_status_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('confirmation_code', sa.Integer(), nullable=True),
    sa.Column('confirmation_tries', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('machines',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('last_semi_service', sa.Date(), nullable=True),
    sa.Column('last_full_service', sa.Date(), nullable=True),
    sa.Column('network_address', sa.String(length=40), nullable=True),
    sa.Column('machine_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_status_id'], ['machine_statuses.machine_status_id'], ),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_table('machine_posts',
    sa.Column('machine_post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.PrimaryKeyConstraint('machine_post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_posts')
    op.drop_table('machines')
    op.drop_table('users')
    op.drop_table('machine_statuses')
    # ### end Alembic commands ###
